# Site settings
title: Breno Sena
email: breno.fsena@gmail.com
description: Desenvolvedor back-end e front-end.
baseurl: ""
url: "https://brenosena.com.br"
github_username: brenofsena

# Build settings
markdown: kramdown
permalink: /:title

sass:
  style: compressed

compress_html:
  clippings: all23
  comments: all
  endings: []
  profile: false

plugins:
  - jekyll-sitemap