# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Breno Sena
email: breno.fsena@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor web e estudante de Sistemas Para Internet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brenosena.com.br" # the base hostname & protocol for your site
github_username: brenofsena

# Build settings
markdown: kramdown
permalink: /:title